name: Deploy to Azure Container App

on:
  push:
    branches:
      - master

env:
  REGISTRY_SERVER: gabrielcolli.azurecr.io
  IMAGE_NAME: docker-test
  IMAGE_TAG: latest
  AZURE_CONTAINER_APP_NAME: docker-test
  AZURE_RESOURCE_GROUP: container-testing
  AZURE_REGION: centralus

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Login to Azure Container Registry
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
     
     #TODO
    #created a docker container and need to copy my actions file into the directory of container  
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Build and deploy Container App
      uses: gabecolli/custom-azure-container-env@v5
      with:
        acrName: gabrielcolli
        acrUsername: ${{ secrets.REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
        appSourcePath: ${{ github.workspace }}
        imageToBuild: gabrielcolli.azurecr.io/docker-test-container
        containerAppName: new-container
        vnetName: isolated-container
        subnetName: containerenv
        location: centralus
        resourceGroup: container-testing
        customContainerAppEnvironment: true
        environmentVariables: |
          testenvvar=gabeiscool
          

    
