name: Deploy to Azure Container App

on:
  push:
    branches:
      - new-test-branch

env:
  REGISTRY_SERVER: gabrielcolli.azurecr.io
  IMAGE_NAME: docker-test
  IMAGE_TAG: latest
  AZURE_CONTAINER_APP_NAME: docker-test
  AZURE_RESOURCE_GROUP: container-testing
  AZURE_REGION: centralus

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Login to Azure Container Registry
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and deploy Container App
      uses: ./gabecolli/docker-test/edit/new-test-branch/.github/workflows/deploy-action.yml
      with:
        acrName: gabrielcolli
        acrUsername: ${{ secrets.REGISTRY_USERNAME }}
        acrPassword: ${{ secrets.REGISTRY_PASSWORD }}
        appSourcePath: ${{ github.workspace }}
        imageToBuild: gabrielcolli.azurecr.io/docker-test-container
        containerAppName: dockercontainername
        resourceGroup: container-testing
        infrastructureResourceSubnetId: /subscriptions/284bc6ed-4e92-4149-aa3d-15d98ce038bf/resourceGroups/container-testing/providers/Microsoft.Network/virtualNetworks/isolated-container/subnets/containerenv
        customContainerAppEnvironment: true
        environmentVariables: |
          testenvvar=gabeiscool
          

    
