name: Trigger auto deployment for new-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/new-container-AutoDeployTrigger-fa3c2c07-a228-4da1-b32e-59d261bad00e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: gabrielcolli.azurecr.io
          username: ${{ secrets.NEWCONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.NEWCONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gabrielcolli.azurecr.io/docker-test-container:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NEWCONTAINER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n new-container -g container-testing --server gabrielcolli.azurecr.io --username  ${{ secrets.NEWCONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.NEWCONTAINER_REGISTRY_PASSWORD }}
            az containerapp update -n new-container -g container-testing --image gabrielcolli.azurecr.io/docker-test-container:${{ github.sha }}
